
  ******  DRILL DATA LIST  ******

                        Date/Time : Wed Aug 01 12:57:51 2012
                        Host Name : "MONBAZILLAC"
                        Directory : "L:\PROJETS_2012\Covidien\Dossier_5_Cartes\3_1_CAO_CR5000_RB0505-03\FAB"
                        User Name : monbazillac

                       <DRP> File : "l:\cr5000\feersc\cr5000\bin\Drill.drp"
                         Comments : ""

                   <PNL/PCB> File : "L:\PROJETS_2012\Covidien\Dossier_5_Cartes\3_1_CAO_CR5000_RB0505-03\ctrb0505-A.pcb"
                  <MRL/MRDB> File : "l:\cr5000\feersc\cr5000\libfee\fee.mrdb"
                    Drill Machine : "EXCELLON"

                  Extended Format : Excellon
                   Character Code : ASCII
                    Record Format : Full Storage
                    Record Length : 512
                     NC Data Unit : Inch
                Coordinate Format : 00V0000
                       Round Unit : 0.00010
        Coordinate Representation : Absolute
                 Omit Coordinates : Off
                    Zero Suppress : Trailing Zero Suppress
 Coordinates during Tool Exchange : Clear
                         EOB Code : LF
                         EOR Code : SPACE
                         ETB Code : SPACE
                         PAD Code : SPACE

                       <DRD> File : ".\per0.drd"
                       <DRL> File : ".\per0.drl"

                        List Unit : Millimeters

                            Layer : Only through holes
                Plating attribute : On
                           Figure : Round/Slot
             Way to output oblong : Alternate (Movement rate:0.25000 Odd number:Off)
             Way to output square : ----------

                           Origin : (   0.00000,   0.00000)
                           Mirror : OFF
                         Rotation : (   0)
                            Scale : (   1.00000)
                           Offset : (   0.00000,   0.00000)

                       Drill Data : 
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 | No. | T_code  | Kind  | Shape |    Size   | Type|Plating|   Hits  |     Move    |   MAX(X,Y)  |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   1 |T01      |Normal |Circle |   0.30480 |   0 |    On |      87 |  1209.57904 |  1141.94590 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   2 |T02      |Normal |Circle |   0.81280 |   0 |    On |       4 |   152.90470 |   143.93926 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   3 |T03      |Normal |Circle |   0.91440 |   0 |    On |      10 |   127.16222 |    96.35998 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   4 |T04      |Normal |Circle |   0.96520 |   0 |    On |       4 |    91.40064 |    80.32750 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   5 |T05      |Normal |Circle |   1.21920 |   0 |    On |      43 |   356.74587 |   336.92084 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   6 |T06      |Normal |Circle |   1.42240 |   0 |    On |       2 |    60.80246 |    60.74410 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   7 |T07      |Normal |Circle |   3.50520 |   0 |    On |       4 |   216.12748 |   212.39988 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |      Total                                              |     154 |  2214.72240 |  2072.63746 |
 +---------------------------------------------------------+---------+-------------+-------------+

                        Data Area : (   2.54000,   3.04800)-(  90.50020,  69.99986)
