
  ******  DRILL DATA LIST  ******

                        Date/Time : Thu Aug 26 15:53:37 2010
                        Host Name : "CYRANO1"
                        Directory : "C:\zuken\home"
                        User Name : cyrano1

                       <DRP> File : "C:\DOCUME~1\FEE1\LOCALS~1\Temp\param2.drp"
                         Comments : ""

                   <PNL/PCB> File : "C:\clients\airox\power-supply-c\pcb\powersupply-c.pcb"
                  <MRL/MRDB> File : "C:\zuken\feersc\cr5000\libfee\fee.mrdb"
                    Drill Machine : "EXCELLON"

                  Extended Format : Excellon
                   Character Code : ASCII
                    Record Format : Full Storage
                    Record Length : 512
                     NC Data Unit : Inch
                Coordinate Format : 00V0000
                       Round Unit : 0.00010
        Coordinate Representation : Absolute
                 Omit Coordinates : Off
                    Zero Suppress : Trailing Zero Suppress
 Coordinates during Tool Exchange : Clear
                         EOB Code : LF
                         EOR Code : SPACE
                         ETB Code : SPACE
                         PAD Code : SPACE

                       <DRD> File : "C:\clients\airox\power-supply-c\fab\per1.drd"
                       <DRL> File : "C:\clients\airox\power-supply-c\fab\per1.drl"

                        List Unit : Millimeters

                            Layer : Only through holes
                Plating attribute : Off
                           Figure : Round/Slot
             Way to output oblong : Alternate (Movement rate:0.25000 Odd number:Off)
             Way to output square : ----------

                           Origin : (   0.00000,   0.00000)
                           Mirror : OFF
                         Rotation : (   0)
                            Scale : (   1.00000)
                           Offset : (   0.00000,   0.00000)

                       Drill Data : 
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 | No. | T_code  | Kind  | Shape |    Size   | Type|Plating|   Hits  |     Move    |   MAX(X,Y)  |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   1 |T01      |Normal |Circle |   2.99720 |   0 |   Off |       1 |   156.09961 |   155.25750 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   2 |T02      |Normal |Circle |   3.20040 |   0 |   Off |       2 |   266.28022 |   265.30046 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   3 |T03      |Normal |Circle |   3.60680 |   0 |   Off |       1 |   221.74947 |   217.29954 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   4 |T04      |Normal |Circle |   4.01320 |   0 |   Off |       4 |   311.67711 |   308.80050 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |   5 |T05      |Normal |Circle |   4.62280 |   0 |   Off |       4 |   375.30291 |   366.99952 |
 +-----+---------+-------+-------+-----------+-----+-------+---------+-------------+-------------+
 |      Total                                              |      12 |  1331.10932 |  1313.65752 |
 +---------------------------------------------------------+---------+-------------+-------------+

                        Data Area : (  16.19250,  25.30094)-(  84.00034, 220.29928)
